steps:
  - name: 'python:3.7-slim'
    id: CompilePipleline
    entrypoint: /bin/sh
    args:
      - '-c'
      - 'pip install -r pipeline/requirements.txt && python pipeline/pipeline.py && ls pipeline/'
artifacts:
  objects:
    location: 'gs://kbc/ccc/pipeline/'
    paths: ['pipeline/pipeline.py.tar.gz']
