steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/customerchurn/serve:latest || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/customerchurn/serve:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/customerchurn/serve:latest'
      - 'serve/'
images: ['gcr.io/$PROJECT_ID/customerchurn/serve:latest']
