apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  name: churn-p-job
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.85
    objectiveMetricName: accuracy
    additionalMetricNames:
      - test-loss    
  algorithm:
    algorithmName: random
  parameters:
    - name: --epochs
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "5"
    - name: --batch_size
      parameterType: int
      feasibleSpace:
        min: "120"
        max: "200"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 1 
              restartPolicy: OnFailure
              template:
                spec:
                  containers:
                    - name: tensorflow 
                      image: gcr.io/kube-2020/customerchurn/train:latest
                      imagePullPolicy: Always
                      command:
                        - "python"
                        - "/train.py"
                        - "--katib=1"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
